name: Hello World Command
on:
  repository_dispatch:
    types: [hello-world-local-command]
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create URL to the run output
        id: vars
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!

            [Click here to see the command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}
